## Кросплатформне програмування Python
### Косенко Іван
*КН23001б*
**Варіант 12**

## Завдання 1

$$
z1 = \frac{\sin(4\alpha)}{1+\cos(4\alpha)} \cdot \frac{\cos(2\alpha)}{1+\cos(2\alpha)}
$$

$$
z2 = \frac{1}{\tan\left(\frac{3}{2}\pi - \alpha\right)}
$$

In [1]:
import math

alpha = 0.5  # можна змінити

z1 = (math.sin(4 * alpha) / (1 + math.cos(4 * alpha))) * \
     (math.cos(2 * alpha) / (1 + math.cos(2 * alpha)))

z2 = 1 / math.tan((3/2) * math.pi - alpha)

print("z1 =", z1)
print("z2 =", z2)

z1 = 0.5463024898437905
z2 = 0.5463024898437907


## Завдання 2

$$
\arctan(x) = -\frac{\pi}{2} + \sum_{k=0}^{n} \frac{(-1)^{k+1}}{(2k+1)x^{2k+1}}
$$

In [2]:
import math

# параметри
x = 0.5
n = 20

# 1 спосіб (вбудована функція)
y1 = math.atan(x)

# 2 спосіб (ряд Тейлора для arctan)
def arctg(x, n):
    return sum(((-1)**k) * x**(2*k+1) / (2*k+1) for k in range(n))

y2 = arctg(x, n)

# результат
print("Через math.atan:", y1)
print("Через ряд:", y2)
print("Похибка:", abs(y1 - y2))
print("Кількість членів:", n)

Через math.atan: 0.4636476090008061
Через ряд: 0.46364760900079716
Похибка: 8.93729534823251e-15
Кількість членів: 20


## Завдання 3

Ущільнити задану матрицю, видаляючи з неї рядки та стовпці, заповнені нулями.
Знайти номер першого рядка, що містить хоча б один додатний елемент.
Матриця 12x14 задана вручну.

In [3]:
import numpy as np

A = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 10, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 13, 14, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 17, 18, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
])

# видалення нульових рядків
A = A[~np.all(A == 0, axis=1)]

# видалення нульових стовпців
A = A[:, ~np.all(A == 0, axis=0)]

print("Ущільнена матриця:")
print(A)

# перший рядок з додатним елементом
row_index = -1

for i in range(A.shape[0]):
    if np.any(A[i] > 0):
        row_index = i
        break

print("Перший рядок з додатним елементом:", row_index)

Ущільнена матриця:
[[ 1  2  0  0]
 [ 3  4  5  0]
 [ 6  7  8  9]
 [10 11 12  0]
 [13 14 15 16]
 [17 18 19  0]]
Перший рядок з додатним елементом: 0
